# Create new review
POST http://localhost:3001/api/training/06cba56f-4490-4794-997a-177fb64c97d5/reviews HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
  "rating": 1,
  "text": "not bad very long description at least 100 symbols again not bad very long description at least 100 symbols"
}
###

# Get
GET http://localhost:3001/api/training/06cba56f-4490-4794-997a-177fb64c97d5/reviews HTTP/1.1
Authorization: Bearer

###
