# Login user by email and password
POST http://localhost:3001/api/user/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyYTg5ZDViNi04MzkxLTQ1YmItYjczOC0yZDQ3MDg4ZGFmMDQiLCJuYW1lIjoiTWlzcyBDaHJpc3R5IEJydWVuLVN0YW50b24gTUQiLCJlbWFpbCI6IkxhbmU1M0Bsb2NhbC5sb2NhbCIsImlhdCI6MTcxMDI0MTk4NSwiZXhwIjoxNzEwMjQyODg1fQ.fzNokNGlYhoyQrKo5v8TEJ1JPdF3oLKYfJIu867Dguc

{
  "email": "Lane53@local.local",
  "password": "123456"
}

###
