version: '3.9'
services:
  fit_friends_postgres:
    image: postgres:14-alpine
    container_name: fit_friends_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - fit_friends_postgres:/var/lib/postgresql/data

    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d {POSTGRES_PASSWORD}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - fit_friends

  fit_friends_pgadmin:
    image: dpage/pgadmin4
    container_name: fit_friends_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - fit_friends_postgres
    networks:
      - fit_friends

volumes:
  fit_friends_postgres:

networks:
  fit_friends:
    driver: bridge
