# Create a new training
POST http://localhost:3001/api/training HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer

--boundary
Content-Disposition: form-data; name="backgroundPicture"; filename="photo-1.png"
Content-Type: image/png

< ../../../../frontend/public/img/content/avatars/users/photo-1.png
--boundary
Content-Disposition: form-data; name="video"; filename="video-1.mp4"
Content-Type: video/mp4

< ../../../../frontend/public/img/content/training-video/video-1.mp4
--boundary
Content-Disposition: form-data; name="title"

Title 1
--boundary
Content-Disposition: form-data; name="level"

любитель
--boundary
Content-Disposition: form-data; name="type"

бег
--boundary
Content-Disposition: form-data; name="duration"

30-50 мин
--boundary
Content-Disposition: form-data; name="price"

1111
--boundary
Content-Disposition: form-data; name="calories"

1111
--boundary
Content-Disposition: form-data; name="description"

Training description 1
--boundary
Content-Disposition: form-data; name="gender"

для всех
--boundary
Content-Disposition: form-data; name="isSpecialOffer"

true
--boundary--

###

###

# Get training info by id
GET http://localhost:3001/api/training/06cba56f-4490-4794-997a-177fb64c97d5 HTTP/1.1
Authorization: Bearer

###

# Update training
PATCH http://localhost:3001/api/training/7b139e97-7e49-41b1-b85c-27d7ad540aaf HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer

--boundary
Content-Disposition: form-data; name="backgroundPicture"; filename="photo-2.png"
Content-Type: image/png

< ../../../../frontend/public/img/content/avatars/users/photo-2.png
--boundary
Content-Disposition: form-data; name="title"

Title 1 updated
--boundary
Content-Disposition: form-data; name="price"

2222
--boundary
Content-Disposition: form-data; name="calories"

3333
--boundary--

###

# Get trainings catalog of current user with role Trainer
GET http://localhost:3001/api/training HTTP/1.1
Authorization: Bearer

###

# Get trainings catalog of current user with role Trainer with filters
GET http://localhost:3001/api/training?limit=3&price=2000&price=1889161061&rating=4 HTTP/1.1
Authorization: Bearer

###
