# Get User's friends list
GET http://localhost:3001/api/account/user/friends HTTP/1.1
Authorization: Bearer

###

# Send notifications about new trainings
POST http://localhost:3001/api/account/user/send-new-trainings-mail HTTP/1.1
Authorization: Bearer

###
