export enum FrontendRoute {
  Intro = '/',
  Login = '/login',
  Registration = '/registration',
  Questionnaire = '/questionnaire',
  Personal = '/personal',
  Main = '/main',
  Users = '/users',
  UserCard = '/user',
  Trainings = '/trainings',
  TrainingCard = '/training',
  Friends = '/friends',
  Notifications = '/notifications',
  Create = '/create',
}
