export enum FrontendRoute {
  Login = 'login',
  Registration = 'registration',
  Questionnaire = 'questionnaire',
  Account = 'account',
  Main = 'main',
  Users = 'users',
  UserCard = 'user',
  Trainings = 'trainings',
  TrainingCard = 'training',
  Friends = 'friends',
  Notifications = 'notifications',
  Create = 'create',
  Orders = 'orders',
  Purchases = 'purchases',
}
